# Generated by Django 4.2.6 on 2023-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(editable=False, max_length=50)),
                ('coupon_code', models.CharField(max_length=50)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coupon_expiry', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
