# Generated by Django 4.2.6 on 2023-12-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
